source 'https://rubygems.org'

gemspec

gem 'websocket_parser', '~> 0.1'
gem 'celluloid', '~> 0.16'
gem 'redis', '~> 3.2'
gem 'celluloid-redis', '>= 0'

group :test do
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
  gem 'simplecov', require: false, group: :test
  gem 'simplecov-console'
end

