require_relative 'support/array'
require_relative 'support/dir'
require_relative 'support/dup'
require_relative 'support/file'
require_relative 'support/hash'
require_relative 'support/string'
require_relative 'support/aargv'
