# frozen_string_literal: true

source "https://rubygems.org"

gem "pakyow", path: "../"

# app server
gem "puma", platforms: :ruby
gem "thin", platforms: :mswin

# use dotenv to load environment variables
gem "dotenv"

group :test do
  gem "rspec"
end

# your gems here
