AllCops:
  TargetRubyVersion: 2.5
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - '**vendor/**/*'
    - '**/spec/**/*'
    - '**/benchmark/**/*'
    - '**/node_modules/**/*'
    - 'pakyow-core/lib/pakyow/generators/**/*'
  DisplayCopNames: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/BlockAlignment:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/UnneededPercentQ:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/AndOr:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

Style/HashSyntax:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: semantic

Style/VariableInterpolation:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Gemspec:
  Enabled: true

Bundler:
  Enabled: true

Naming:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
