format: progress
parallel: true

ignore:
  - '**/spec/**/*'
  - 'core/lib/pakyow/behavior/running.rb':
    - Lint/NestedMethodDefinition
  - 'core/lib/pakyow/generator/processor.rb':
    - Lint/ErbNewArguments
  - 'core/lib/pakyow/loader/context.rb':
    - Security/Eval
  - 'core/lib/pakyow/runnable/errors.rb':
    - Lint/InheritException
  - 'core/lib/pakyow/task.rb':
    - Security/Eval
  - 'frameworks/data/lib/pakyow/data/sources/relational.rb':
    - Style/ClassEqualityComparison
  - 'frameworks/mailer/lib/pakyow/mailer/framework.rb':
    - Lint/UnderscorePrefixedVariableName
  - 'frameworks/reflection/lib/pakyow/reflection/framework.rb':
    - Lint/NestedMethodDefinition
  - 'support/lib/pakyow/support/handleable.rb':
    - Lint/RescueException
  - 'frameworks/ui/lib/pakyow/application/behavior/ui/rendering.rb':
    - Style/ClassEqualityComparison
