format: progress
parallel: true

ignore:
  - '**/spec/**/*'
  - 'pakyow-core/lib/pakyow/behavior/running.rb':
    - Lint/NestedMethodDefinition
  - 'pakyow-core/lib/pakyow/loader/context.rb':
    - Security/Eval
  - 'pakyow-core/lib/pakyow/task.rb':
    - Security/Eval
  - 'pakyow-mailer/lib/pakyow/mailer/framework.rb':
    - Lint/UnderscorePrefixedVariableName
  - 'pakyow-support/lib/pakyow/support/handleable.rb':
    - Lint/RescueException
  - 'pakyow-reflection/lib/pakyow/reflection/framework.rb':
    - Lint/NestedMethodDefinition
