#!/usr/bin/env ruby
# frozen_string_literal: true

# Automatically run with bundler.
#
current_path = File.expand_path(".")
binstub_path = File.join(current_path, "bin/pakyow")
if !defined?(Bundler) && File.exist?(binstub_path)
  exec "#{binstub_path} #{ARGV.join(" ")}"
else
  require "pakyow/cli"
  Pakyow::CLI.new
end
