source 'https://rubygems.org'
<% local_pakyow = Gem::Specification.sort_by{ |g| [g.name.downcase, g.version] }.group_by{ |g| g.name }.detect{|k,v| k == 'pakyow'} %>
<% if !local_pakyow || local_pakyow.last.last.version < Gem::Version.new(Pakyow::VERSION) %>
gem 'pakyow', github: 'pakyow/pakyow'
<% else %>
gem 'pakyow', '~> 0.10'
<% end %>
# app server
gem 'puma', platforms: :ruby
gem 'thin', platforms: :mswin

# use dotenv to load environment variables
gem 'dotenv'

group :test do
  gem 'rspec'
end

# your gems here
