source 'https://rubygems.org'

# live on the edge and uncomment this line
# gem 'pakyow', github: 'pakyow/pakyow'

# use the latest released version
gem 'pakyow', '~> 0.10'

# app server
gem 'puma', platforms: :ruby
gem 'thin', platforms: :mswin

# use dotenv to load environment variables
gem 'dotenv'

group :test do
  gem 'rspec'
end

# your gems here
