# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: "../../"
gemspec path: "../../pakyow-data"
gemspec path: "../../pakyow-presenter"
gemspec path: "../../pakyow-realtime"
gemspec path: "../../pakyow-routing"
gemspec path: "../../pakyow-support"
gemspec path: "../../pakyow-ui"

gem "http"
gem "puma"
gem "sqlite3"
